# 年份选择范围配置
year_start: 2021
year_end: 2051

# 百万以下数据配置
below_million:
  workbook_name: "百万以下"
  sheet_name: "百万以下"
  required_cols:
    # 不要更改顺序，必要时仅在原位置修改
    - 集团商机编码
    - 单元
    - 行业标识
    - 预计签约日期
    - 商机预测金额(万元)
    - 商机名称 # 用于展示top10

# 百万以上数据配置
above_million:
  workbook_name: "百万以上"
  sheet_name: "百万以上"
  required_cols:
    # 不要更改顺序，必要时仅在原位置修改
    - 集团商机编码
    - 单元
    - 行业标识
    - 预计签约时间
    - 预估签约金额(万元)
    - 是否目标时间段
    - 商机名称 # 用于展示top10

# 签约情况数据配置
contract_status:
  workbook_name: "签约情况"
  sheet_name: "签约清单"
  required_cols:
    # 不要更改顺序，必要时仅在原位置修改
    # - 比对  # 实际签约数据中，需要删去"比对"列内容包含"集成""陕数""省公司"的合同，现在没这个需求
    - 商机编码
    - 单元（新）
    - 行业（新）
    - 签约日期
    - 省口径签约额

# 商机编码数据配置，用于严口径统计时对签约情况进行筛选
biz_code:
  workbook_name: "商机编码"
  sheet_name: "Sheet1"
  required_cols:
    # 不要更改顺序，必要时仅在原位置修改
    - 集团商机编码
    - 预计签约日期

# 合同排除关键词，目前无此需求
# contract_exclude_keywords:
#   - 集成
#   - 陕数
#   - 省公司

# 单位（固定顺序），与通报模板保持一致
unit_order:
  - 要客行业
  - 金融交通
  - 住建应急
  - 卫健行业
  - 农业文宣
  - 商业客户
  - 工业企业
  - 党政行业
  - 教育行业
  - 软信服
  - 高新
  - 经开
  - 莲湖
  - 雁塔
  - 新城
  - 碑林
  - 未央
  - 灞桥
  - 辛家庙
  - 曲江
  - 南高新
  - 西航
  - 浐灞国际港
  - 长安
  - 临潼
  - 鄠邑
  - 高陵
  - 阎良
  - 周至
  - 航天
  - 杨凌
  - 蓝田
  - 沣东
  - 沣西

# 行业（固定顺序），与通报模板保持一致
industry_order:
  - 党政行业事业部
  - 工业企业行业事业部
  - 教育行业事业部
  - 金融交通行业事业部
  - 农业文宣行业事业部
  - 软信服行业事业部
  - 商业客户事业部
  - 卫健行业事业部
  - 要客行业事业部
  - 住建应急行业事业部

# 列标签顺序：
col_order:
  - 计划签约量
  - 实际签约量
  - 转签率
  - 计划签约金额
  - 实际签约金额
  - 五十万以下计划签约量
  - 五十万以下实际签约量
  - 五十万以下计划签约金额
  - 五十万以下实际签约金额
  - 五十至百万计划签约量
  - 五十至百万实际签约量
  - 五十至百万计划签约金额
  - 五十至百万实际签约金额
  - 百万以上计划签约量
  - 百万以上实际签约量
  - 百万以上计划签约金额
  - 百万以上实际签约金额

